apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vidfetch-bot.fullname" . }}-secret
  labels:
    {{- include "vidfetch-bot.labels" . | nindent 4 }}
data:
  token: {{ required "You must provide your bot API token" .Values.botToken | b64enc }}
